server:
  port: 8080
  ssl:
    enabled: false

management:
  server:
    port: 8081
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus